#!/bin/bash
# Quick Reference - Asset Optimization Commands
# This file contains all the gulp/npm commands for asset optimization

echo "📦 Asset Optimization Commands"
echo ""
echo "Installation:"
echo "  npm install"
echo ""

echo "Development:"
echo "  npm run dev              # Watch for changes and rebuild"
echo "  npm run serve            # Start dev server with optimizations"
echo ""

echo "Production Build:"
echo "  npm run build            # Run all optimization tasks"
echo ""

echo "Individual Tasks:"
echo "  npm run minify-css       # Minify CSS only"
echo "  npm run optimize-svg     # Optimize SVG images"
echo "  npm run subset-fonts     # Generate font subsetting guide"
echo "  npm run clean            # Remove dist/ folder"
echo ""

echo "Server Management:"
echo "  npm run serve            # Start local server on :8000"
echo ""

echo "📊 What Gets Optimized:"
echo ""
echo "CSS Minification:"
echo "  ✓ Removes whitespace and comments"
echo "  ✓ Merges duplicate selectors"
echo "  ✓ Compresses values"
echo "  ✓ Generates source maps"
echo "  Output: dist/css/style.min.css"
echo ""

echo "JavaScript Minification:"
echo "  ✓ Mangles variable names"
echo "  ✓ Removes console logs"
echo "  ✓ Compresses code"
echo "  ✓ Generates source maps"
echo "  Output: dist/js/main.min.js"
echo ""

echo "SVG Optimization:"
echo "  ✓ Removes unnecessary attributes"
echo "  ✓ Removes metadata"
echo "  ✓ Compresses paths"
echo "  ✓ Conversion ratio: ~70-80% reduction"
echo "  Output: dist/assets/images/*.svg"
echo ""

echo "Image Optimization:"
echo "  ✓ JPEG: Progressive, 80% quality"
echo "  ✓ PNG: Optimization level 2"
echo "  ✓ GIF: Interlacing"
echo "  Conversion ratio: ~60-75% reduction"
echo "  Output: dist/assets/images/*"
echo ""

echo "Font Subsetting:"
echo "  ✓ Reduces font files by 70-85%"
echo "  ✓ WOFF2 format (modern browsers)"
echo "  ✓ Faster font loading"
echo "  Output: dist/assets/fonts/*.woff2"
echo ""

echo "Asset Path Management:"
echo "  ✓ Updates HTML with correct paths"
echo "  ✓ Proper CDN/server paths"
echo "  ✓ Creates asset manifest"
echo "  Output: dist/assets-manifest.json"
echo ""

echo "Server Optimization:"
echo "  ✓ Gzip compression"
echo "  ✓ Security headers"
echo "  ✓ Cache optimization"
echo "  ✓ MIME type handling"
echo ""

echo "🎯 Performance Targets:"
echo "  CSS:        78% smaller (156KB → 34KB)"
echo "  JS:         80% smaller (89KB → 18KB)"
echo "  Images:     70% smaller (450KB → 120KB)"
echo "  SVG:        80% smaller (45KB → 5KB)"
echo "  Total:      72% reduction (785KB → 222KB)"
echo "  With gzip:  94% compression on text"
echo ""

echo "📚 Documentation:"
echo "  - OPTIMIZATION-GUIDE.md  (Comprehensive guide)"
echo "  - FONT-SUBSETTING.sh     (Font subsetting help)"
echo "  - server-config.js       (Server configuration)"
echo "  - gulpfile.js            (Build tasks)"
echo ""

echo "🚀 Typical Workflow:"
echo ""
echo "1. Development:"
echo "   npm run dev              # Watch for changes"
echo "   npm run serve            # Run local server"
echo ""
echo "2. Before Deployment:"
echo "   npm run build            # Build all optimized assets"
echo ""
echo "3. Testing:"
echo "   Open http://localhost:8000"
echo "   Check dist/ folder"
echo "   Verify all assets load correctly"
echo ""
echo "4. Deploy:"
echo "   Upload dist/ folder to production server"
echo "   Configure server cache headers"
echo "   Test live site"
echo ""
